### ISSUE TITLE
Entity name 

### ISSUE THREAD

**Issue by Medi64** [websylv/homeassistant-meteoswiss#1]
Hi, 

thank you for providing this component. Finally we have a accurate weather component available for Switzerland. Great job. I installed it on macOS and my Raspi. Both work fine with no issues so far. (There was an installation issue with the Raspi with the  meteoswiss packages and all the dependencies but I think these is a known issue with numpy. However after manual installation of all dependencies it worked fine on the Raspi)

Would it make sense to change the entity from weather.<station_name> into weather.meteoswiss ? 

<img width="502" alt="Bildschirmfoto 2020-02-16 um 10 15 08" src="https://user-images.githubusercontent.com/49900773/74602066-3c512c00-50a5-11ea-8077-9743e6db9896.png">

The station name could cause confusion as it differers from the actual location, but <meteoswiss> is well known :-). However, this is a minor issue. Great job!

Cheers
Medi64

**Comment by websylv** [comment]
Hello

Thank you for the feedback
I published a new release, now if you want you can add to your config the 

 ` name: meteoSwiss`

for the issue with the raspberry i will check before releasing to HACS

**Comment by Medi64** [comment]
> Hello
> 
> Thank you for the feedback
> I published a new release, now if you want you can add to your config the
> 
> ` name: meteoSwiss`
> 
> for the issue with the raspberry i will check before releasing to HACS
> So far I only worked on x64 env

Hi

Thank you that works perfect.
