### ISSUE TITLE
not visible with new release 0.110.0

### ISSUE THREAD

**Issue by chris669** [websylv/homeassistant-meteoswiss#11]
hi, sorry, tried to search for meteo-swiss, but nothing. Deleted the lines in configuration. Maybe related to new 0.110.0?
![Screenshot_20200520-162321](https://user-images.githubusercontent.com/15046400/82458246-b931de80-9ab6-11ea-8904-38829075c8f5.png)

**Comment by websylv** [comment]
did you restart after installing ?
i tested for me it's fine with the 0.110

**Comment by chris669** [comment]
deleted lines in configuration file, restarted HA, checked that my swissmeteo card was no more there, went in configuration, try to add, couldn't find it

**Comment by swissMack** [comment]
Updated to 0110, deleted entry from configuration.yaml, restarted, found Meteo-swiss entry in Integrations, was able to configure location/postcode etc., all successful. However no card in Lovelace and not visible as sensor entity

**Comment by chris669** [comment]
sorry but do I still have to copy the hacks and info files in custom_components? Because normally if the components are HA integrated, you do not have to do that.
