### ISSUE TITLE
Integration not appearing in list

### ISSUE THREAD

**Issue by nasgulch** [websylv/homeassistant-meteoswiss#14]
Great work. Thanks for this component. 
Just upgraded to 0.1104 and the integration does not appear in the list anymore
![meteoswiss](https://user-images.githubusercontent.com/61022883/83377262-5c4af800-a3d5-11ea-974e-705b1fab3b1b.png)

**Comment by dxdx65** [comment]
same here, no way to see it in the list.

**Comment by chris669** [comment]
had the same problem, solved by uploading the new code in the custom_components folder, I thought it was no longer needed...

**Comment by nasgulch** [comment]
Well I copied the component but getting a configuration error now

![image](https://user-images.githubusercontent.com/61022883/83840184-389def80-a6fe-11ea-8fce-ef4dcbd5206d.png)

Is the config entry required or not?

**Comment by chris669** [comment]
no, jus delete config and reboot

**Comment by nasgulch** [comment]
Solved
