### ISSUE TITLE
MeteoSwiss plugin cannot be found in Integration after installing - Please provide documentation for manual configuration

### ISSUE THREAD

**Issue by frederickjh** [websylv/homeassistant-meteoswiss#17]
Hi!
I had not reboot my computer with Home Assistant on in not restarted Home Assistant in a long time. However today I did reboot the computer. After this Home Assistant did not start. I checked the log and found a log entry about the MeteoSwiss plugin. I found this github repository and then saw the notice about upgrading. I removed all the configuration from my `configuration.yaml` file. I upgraded the plugin. Then I tried to follow the instructions to configure it in the web UI but when I searched for "meteo" it did not show up, so I was unable to configure it.
It seems that even though this plugin can be installed via HACS, for some reason is no longer listed under integrations per the instructions to configure it.

Can you please add documentation on how to configure this plugin manually?
I have it installed and did check that it is the latest version. I just need to know how to configure it since the old configuration no longer works.

Thanks in advance for any help you can provide!
Frederick

**Comment by jukindle** [comment]
I solved it by following these steps:

1. Copy the custom component into your folder.
2. Add "meteo-swiss:" to your configuration
3. Restart home assistant
4. Remove the line again from your configuration and restart.
5. Now, it was listed on the integrations page.

**Comment by frederickjh** [comment]
@jukindle are you manually copying the custom component in the `home_assistant/custom_component/` directory or are you using HACS. When I install or uninstall I see the `meteo-swiss` appear or disapear.

> 2. Add "meteo-swiss:" to your configuration

Do you mean add the old configuration back in? Like so:
```yaml
weather:
  - platform: meteo-swiss
    name: MeteoSwiss
    postcode: 8000
```

I went through the steps you outlined above using HACS to copy the custom component in, but when I go to integrations and try to add a new one Meto Swiss does not show up in the list.

I noticed that there was an error in the log related to this module. Not sure if that will help to solve this.

> Platform error weather.meteo-swiss - cannot import name 'SPEED_KILOMETERS_PER_HOUR' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
2:52 AM components/homeassistant/__init__.py (ERROR)

However I just realized that I am a few version behind the current version of Home Assistant and only on Home Assistant 0.105.2.

**Comment by frederickjh** [comment]
Closing as I got this working. Basically this HA integration moved from being configured in the `configuration.yaml` file to being configured in the GUI. Looks like in the process it can get confused. I did get this working by commenting out and restarting, but I am no longer exactly sure what fixed it.
