### ISSUE TITLE
Issues with newest beta (0.115)

### ISSUE THREAD

**Issue by frog32** [websylv/homeassistant-meteoswiss#21]
Using 0.115b3 I get the following error:

```Setup failed for meteo-swiss: Unable to import component: cannot import name 'UNIT_PERCENTAGE' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)```

**Comment by websylv** [comment]
you can download the source and replace by hand the const.py
i will push a new release when the 0.115 is released

**Comment by frog32** [comment]
No worries, just wanted to ensure that you get a bug report as early as possible. Thanks for the fix.
