### ISSUE TITLE
Guide for absolute beginners

### ISSUE THREAD

**Issue by yvansandoz** [websylv/homeassistant-meteoswiss#27]
Hello,

Could you please briefly describe where which files goes in the Home Assistant folder structure? I do run Home Assistant in Docker.

Thank you in advance,
Yvan

**Comment by websylv** [comment]
i think the best is to not install by hand but to use HACS 
you can find the installation guide for HACS here : https://hacs.xyz/docs/installation/manual

**Comment by yvansandoz** [comment]
Thank you, you made my day!!!
