### ISSUE TITLE
Installation failed on HA 0.117.2

### ISSUE THREAD

**Issue by Gulivertx** [websylv/homeassistant-meteoswiss#28]
Hi,
I'm not able to install it on my HA 0.117.2.
The repository is correctly installed from HACS and I restarted HA.
Then I go to my HA Settings -> Integration -> Add -> MeteoSwiss then HA open the modal window and said that I have to wait during the installation, but at the end nothing append...

**Comment by bfritscher** [comment]
try https://github.com/websylv/homeassistant-meteoswiss/issues/30#issuecomment-756950258

**Comment by Gulivertx** [comment]
OK  finally found the problem.
First my python build wasn't support bz2, I had to install libbz2-dev.
Second I also had to add the python package geopy.

After that all works as expected.
