### ISSUE TITLE
How to change station after setup?

### ISSUE THREAD

**Issue by samira734MO** [websylv/homeassistant-meteoswiss#32]
Hello everybody,

Is there a way to change the station, from e.g. SMA to UST, manually after the setup ? I have not found any possibility in the instructions. A new installation did not help. The settings window no longer opened. Also there is no options button under the integration.

Log:
021-03-05 17:00:39 DEBUG (SyncWorker_3) [hamsclient.client] INIT meteoswiss client : name = Mönchaltorf station = SMA postcode = 8617

Thank you very much for your help.

**Comment by muth-zhaw** [comment]
To change the station, you need to add the integration again.

Have a look at [this guide](https://home-assistant-guide.com/2020/09/23/how-to-integrate-meteoswiss-with-home-assistant/).  


**Setting up the MeteoSwiss integration**

MeteSwiss is now installed on your system. However, the integration is not yet set up. To do so, you’ll want to head over to the integrations (found under Configuration in the menu). From there, click on the big plus button and once again search for MeteoSwiss. Select it, and you will be prompted to enter a postal code and station name.

**Comment by samira734MO** [comment]
Thank you for your advice to add the integration again. I had tried that in the meantime and so i could change the station successfully.

Great weather integration for Switzerland especially together with the animated weather card.
