### ISSUE TITLE
Missing version key in manifest

### ISSUE THREAD

**Issue by valentingc** [websylv/homeassistant-meteoswiss#33]
Since Home Assistant 2021.03, there is a deprecation notice for custom integrations that have not set the `version` key in their manifest. It should be added.

This is the log output:
`2021-03-07 13:19:33 WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'meteo-swiss'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'meteo-swiss'`

**Comment by braetkuegeli** [comment]
This issue should be fixed before Home Assistant 2021.6.
`No 'version' key in the manifest file for custom integration 'meteo-swiss'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'meteo-swiss'`
