### ISSUE TITLE
Integration is not supported by Home Assistant 2021.3

### ISSUE THREAD

**Issue by 29axe** [websylv/homeassistant-meteoswiss#35]
This integration raised errors in logs and made HA constantly restarting. 
I remember seeing a message in the logs:
You are using a custom integration meteo-swiss which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

I also had stack traces related to meteo-swiss but sadly I did not catch the logs.

I tried to reinstall the addon but after uninstallation it does not show up anymore in the list of addons in HA.

Core: core-2021.3.4
Supervisor: supervisor-2021.03.6

**Comment by websylv** [comment]
fix in relaese 1.3
