### ISSUE TITLE
'version' key missing

### ISSUE THREAD

**Issue by beatdoebeli** [websylv/homeassistant-meteoswiss#36]
Hi,

as I installed meteo-swiss today, the log file told me:

No 'version' key in the manifest file for custom integration 'meteo-swiss'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'meteo-swiss'

That's what I'm doing here ;-)

**Comment by error33-priv** [comment]
Same issue here, would be great if a fix could be provided!

**Comment by websylv** [comment]
fix in relaese 1.3
