### ISSUE TITLE
Postcode problem

### ISSUE THREAD

**Issue by zufivan** [websylv/homeassistant-meteoswiss#4]
Hi, thanks for your great work, i tried to put postcode 6900 but the weather results show me (Geneva weather) 
following my configuration:
weather:
  - platform: meteo-swiss
    name: "MeteoSwiss"
    postcode: 6900
    station: LUG
Thanks Ivan

**Comment by websylv** [comment]
Hello

Ok i found the issue. I published a new release (0.5) this should correct the issue.


Meteo Swiss data for lugano: 

![chrome_ID4HniWNDF](https://user-images.githubusercontent.com/19144629/75663791-b1119200-5c71-11ea-8d70-408488c96e9c.png)

Home Assistant display :

![chrome_PBqGffGaDb](https://user-images.githubusercontent.com/19144629/75663799-b40c8280-5c71-11ea-856d-65c122433b46.png)

Meteo Swiss data for geneva:

![chrome_vcUHuIPd1t](https://user-images.githubusercontent.com/19144629/75663803-b5d64600-5c71-11ea-83c7-7f921a181a2d.png)

**Comment by zufivan** [comment]
TOP!! Now is working perfect!!
Thanks for your awesom work.

**Comment by zufivan** [comment]
I have another problem, the temperature in Homeassistant isn't corrert from Meteoswiss.. below print screnn:
![image](https://user-images.githubusercontent.com/47624226/75708367-f7daa880-5cc0-11ea-8e5e-9a25ffbc6f2f.png)

![image](https://user-images.githubusercontent.com/47624226/75708382-ff01b680-5cc0-11ea-93e6-c46c14f14d6a.png)

Thanks Ivan

**Comment by zufivan** [comment]
Also Wind is wrong.

Regards Ivan

**Comment by CamFlyerCH** [comment]
I also only get the data of the Cointrin weather station, not the one closest or the station I specify. I I don't set the name: parameter my entity changes the name to the station, for example weather.bantiger, but the measurements are still exactly the same as in the Meteoswiss Android App for Geneva.

**Comment by CamFlyerCH** [comment]
I think the problem is in hassio that uses an old version of meteoswiss, since in 0.0.5 GVE was hardcoded;
`def get_current_condition(station):
    data = pd.read_csv("https://data.geo.admin.ch/ch.meteoschweiz.messwerte-aktuell/VQHA80.csv",sep=';',header=1)
    stationData = data.loc[data['stn'].str.contains('GVE')]
    stationData = stationData.to_dict('records')
    return stationData`

But I don't know how I can update it to 0.0.11

**Comment by CamFlyerCH** [comment]
I was able to find a way to execute pip3 freeze and can confirm that there is 0.0.11 installed. Also after a complete reboot no luck ! Exactly the same data from the station GVE

Debug log:
2020-03-19 00:32:33 DEBUG (MainThread) [custom_components.meteo-swiss.weather] Configuration :
2020-03-19 00:32:33 DEBUG (MainThread) [custom_components.meteo-swiss.weather] name: auto
2020-03-19 00:32:33 DEBUG (MainThread) [custom_components.meteo-swiss.weather] lat: 46.[redacted]
2020-03-19 00:32:33 DEBUG (MainThread) [custom_components.meteo-swiss.weather] lon: 7.[redacted]
2020-03-19 00:32:33 DEBUG (MainThread) [custom_components.meteo-swiss.weather] station: BER
2020-03-19 00:32:33 DEBUG (MainThread) [custom_components.meteo-swiss.weather] postcode: [redacted]
2020-03-19 00:32:33 DEBUG (MainThread) [custom_components.meteo-swiss.weather] meteo-swiss INIT
2020-03-19 00:32:33 DEBUG (MainThread) [custom_components.meteo-swiss.weather] Using fixed post code : [redacted]
2020-03-19 00:32:33 DEBUG (MainThread) [custom_components.meteo-swiss.weather] Using fixed station code : BER
2020-03-19 00:32:33 DEBUG (MainThread) [custom_components.meteo-swiss.weather] meteo-swiss async update
2020-03-19 00:32:34 DEBUG (MainThread) [custom_components.meteo-swiss.weather] Current symbol is 101 condition is : clear-night

Entity:
temperature: 7.3
humidity: 84
pressure: 976.7
wind_bearing: WNW
wind_speed: 1.4
attribution: Weather forecast from MeteoSwiss (https://www.meteoswiss.admin.ch/)
forecast: 
- datetime: '2020-03-20'
  templow: 5
  temperature: 17
  condition: partlycloudy
- datetime: '2020-03-21'
  templow: 4
  temperature: 11
  condition: rainy
- datetime: '2020-03-22'
  templow: 2
  temperature: 9
  condition: rainy
- datetime: '2020-03-23'
  templow: -1
  temperature: 11
  condition: partlycloudy
- datetime: '2020-03-24'
  templow: -2
  temperature: 14
  condition: partlycloudy

friendly_name: Bern / Zollikofen

**Comment by jiiins** [comment]
Now it seems that the postcode is ignored entirely. Even if I input your Geneva postcode 1201, I get the Lugano results (close to where I am but not exact).

**Comment by zufivan** [comment]
HI all,
I did some more tests, with this configuration: 
weather:
  - platform: meteo-swiss
    postcode: 6900
    station: LUG
The forecast is working perfect temp min, max and icons.
But the current condition (temperature, wind, umidity and pressure) is showing Geneva.  (checkend from the file https://data.geo.admin.ch/ch.meteoschweiz.messwerte-aktuell/VQHA80.csv

Thanks Ivan

**Comment by CamFlyerCH** [comment]
I just uninstalled in HACS and then selected "master" as the version and reinstalled it again. 
![image](https://user-images.githubusercontent.com/25889580/79074153-12a23300-7ceb-11ea-8113-3e278c0ebce9.png)

### **_Now it works !_**
![image](https://user-images.githubusercontent.com/25889580/79074230-83494f80-7ceb-11ea-926d-ac02f0c250e9.png)

![image](https://user-images.githubusercontent.com/25889580/79074267-bab7fc00-7ceb-11ea-9e99-abc9fd6f4f4e.png)

**Comment by zufivan** [comment]
Hi all,

I tried like Jean-Marc to uninstall in HACS and then selected "master" as the version and reinstalled it again.
It works fine. 
Thanks a lot
