### ISSUE TITLE
Actual temperature is taken from "weather station" instead of calculated value for zip code

### ISSUE THREAD

**Issue by dawiinci** [websylv/homeassistant-meteoswiss#57]
In the Swiss Meteo app I get the actual temperature in accuracy to 0.1°C to my own sensors. 

However the plugin gives me the value of the nearest weather station, which is far away: 1.8°C instead of 5.7°C. 

The forecast matches the app though.

My conclusion ist, the weather entity shows the temperature (and possibly weather conditions) for the weather station instead of the zip code.

**Comment by badewanne1234** [comment]
thats right, it pulls the data from the nearest weather station to your location. (You can force it to use another weather station from the swiss meteo network - see the readme).

**Comment by dawiinci** [comment]
But wouldn’t the actual (calculated) value be more valuable? Just like in the app?

**Comment by schneich** [comment]
I would be interested in the actual weather of my location as well, because the next weather station is too far away.

**Comment by badewanne1234** [comment]
I'm not sure if that calculated data is exposed by meteoswiss.
Regardless, accurate weather is crucial for my automations, thats why I bought a weather station eventually. 😉
I use meteoswiss for forecast though

**Comment by schneich** [comment]
@badewanne1234 what weather station did you buy? How does it integrate with e.g. HomeAssistent?

**Comment by badewanne1234** [comment]
I bought a Weatherflow Tempest.
It beautifully integrates into HA with this integration: https://github.com/briis/hass-weatherflow2mqtt
I even went further to generate the local weather condition as much as possible, see here: https://github.com/briis/hass-weatherflow2mqtt/issues/17#issuecomment-1093340617

**Comment by dawiinci** [comment]
I use online data to backup my own sensors. But met.no is much more accurate, simply because the weather station is too far away. And there isn’t any other nearby on the same sea level.

**Comment by badewanne1234** [comment]
@dawiinci why should met.no be more accurate if they dont have a measurement-station nearby, can you explain more detailed?

**Comment by dawiinci** [comment]
As far as I know they use existing weather stations as well and use algorithms to determine the probable conditions at a ny given place (just like Swiss Meteo does). Unless you live next to the station this is very misleading. For example my next station is 200 m higher, another one is far away in an area where the weather is always different due to topography.

I guess they are taking these conditions into account and calculate the conditions. Just like they do with the Pollen concentration.
