### ISSUE TITLE
Add more data

### ISSUE THREAD

**Issue by nliaudat** [websylv/homeassistant-meteoswiss#6]
Hi, 
1st thank you very much for the development !

My suggestion for improvement would be to add the other data available, namely:
rre150z0    mm          Precipitation; ten minutes total
sre000z0    min         Sunshine duration; ten minutes total
gre000z0    W/m²        Global radiation; ten minutes mean
fu3010z1    km/h        Gust peak (one second); maximum

and perhaps wind bearing (dkl010z0) in degree in addition to the transformation done in SW, NW, etc. 

Best Regards
Nicolas

**Comment by websylv** [comment]
it will be availaible in the next release as a sensor

**Comment by websylv** [comment]
i published a new release 
please read the doc ! you need to do manual action before and after the upgrade
