### ISSUE TITLE
Overriding deprecated methods on an instance of WeatherEntity - unsupported from Home Assistant 2023.1.

### ISSUE THREAD

**Issue by serotonie** [websylv/homeassistant-meteoswiss#67]
Hi there,

Just fyi 

`WARNING (MainThread) [homeassistant.components.weather] custom_components.meteo-swiss.weather::MeteoSwissWeather is overriding deprecated methods on an instance of WeatherEntity, this is not valid and will be unsupported from Home Assistant 2023.1. Please report it to the custom integration author`

Cheers

**Comment by Siggy101** [comment]
I confirm I have the same warning:

Logger: homeassistant.components.weather
Source: components/weather/__init__.py:198
Integration: Weather (documentation, issues)
First occurred: 11:43:47 (1 occurrences)
Last logged: 11:43:47

custom_components.meteo-swiss.weather::MeteoSwissWeather is overriding deprecated methods on an instance of WeatherEntity, this is not valid and will be unsupported from Home Assistant 2023.1. Please report it to the custom integration author.

**Comment by serotonie** [comment]
I didn't take the time to study in depth the source of this problem and I also didn't find any real documentation about it.
@Siggy101 do you have any ideas ?

I mean, we still have a little bit of time, but the integration won't work from January 2023 if I understand it correctly.

**Comment by Siggy101** [comment]
I'm afraid I know nothing of what it is overriding nor of the fix.  I found your issue report when I came here to post it myself.
I'm hoping that the MeteoSwiss devs know more about this....
Guys & gals, can you help please?

**Comment by addich** [comment]
there are many other wether integrations with had the same messages. here two examples what they had to do...
hope that helps?

https://github.com/home-assistant/core/pull/74043/files/ffaa440c5a64af18b18b52c9b8f2e391a7f72ab9
https://github.com/home-assistant/core/pull/74297/files/cb7e71418c3945ee6de1625e2435a78b30eb9fb1

**Comment by vistalba** [comment]
Any progress on this issue as 2023.1 is around the corner?

**Comment by neuhausf** [comment]
… aaaaaand its here. Can someone with more python skills than me please fix it?
https://developers.home-assistant.io/blog/2022/12/07/unit_system_changes/

**Comment by serotonie** [comment]
Just updated to 2023.1.0 and so far still working like before.
The message is still present in the logs

**Comment by braetkuegeli** [comment]
I've created a patch and pull request: https://github.com/websylv/homeassistant-meteoswiss/pull/77

**Comment by Rudd-O** [comment]
This is merged already — why would the ticket remain open???

**Comment by serotonie** [comment]
> This is merged already — why would the ticket remain open???

Perhaps because we still need a new release for HACS to be able to propose the update ?

**Comment by serotonie** [comment]
Thx 👍
