### ISSUE TITLE
Error since 2024.07

### ISSUE THREAD

**Issue by matteocorti** [websylv/homeassistant-meteoswiss#93]
Since last update, I am getting:

```
Setup failed for custom integration 'meteo-swiss': Requirements for meteo-swiss not found: ['hamsclient==0.2.3'].
```

**Comment by subw0ofer** [comment]
Same here. 

I am not even able to delete the integration because it is not able to load :( 
Any advice how to delete the integration?

**Comment by braetkuegeli** [comment]
Switched to this fork:

https://github.com/Rudd-O/homeassistant-meteoswiss#how-to-migrate-away-from-websylvs-integration
